### ISSUE TITLE
Unable to use Package in dockerized web application

### ISSUE THREAD

**Issue by JamesIlling** [densen2014/BootstrapBlazor.Geolocation#3]
I am currently unable to run my  WebAssemby project from docker as which it starts up it gets:

```
System.IO.DirectoryNotFoundException
  HResult=0x80070003
  Message=C:\root\.nuget\fallbackpackages2\bootstrapblazor.geolocation\7.0.1\staticwebassets\
  Source=Microsoft.Extensions.FileProviders.Physical
  StackTrace:
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.<>c.<UseStaticWebAssetsCore>b__1_0(String contentRoot)
   at Microsoft.AspNetCore.StaticWebAssets.ManifestStaticWebAssetFileProvider..ctor(StaticWebAssetManifest manifest, Func`2 fileProviderFactory)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssetsCore(IWebHostEnvironment environment, Stream manifest)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssets(IWebHostEnvironment environment, IConfiguration configuration)
   at Microsoft.AspNetCore.WebHost.<>c.<ConfigureWebDefaults>b__9_0(WebHostBuilderContext ctx, IConfigurationBuilder cb)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass9_0.<ConfigureAppConfiguration>b__0(HostBuilderContext context, IConfigurationBuilder builder)
   at Microsoft.AspNetCore.Hosting.BootstrapHostBuilder.RunDefaultCallbacks(ConfigurationManager configuration, HostBuilder innerBuilder)
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(WebApplicationOptions options, Action`1 configureDefaults)
   at Microsoft.AspNetCore.Builder.WebApplication.CreateBuilder(String[] args)
   at PhotoScout.Server.Program.Main(String[] args) in D:\Software\PhotoScountNoAuth\PhotoScount\Server\Program.cs:line 11
```

Is there a simple fix of adding something to the docker file (which is the default). This runs fine from Kestrel or from IISExpress

**Comment by densen2014** [comment]
Sorry, I don't use docker very much, the project is open source, you can try to fix it and provide pr
